name: Build Sprint Indicator
on:
  - push

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Get Shortened Commit SHA
        id: shorten_commit_sha
        uses: iendeavor/shorten-commit-sha@v2.0.0
        with:
          length: 7

      - name: Setup Java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: graalvm
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.1.0

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload Sprint Indicator Jar
        uses: actions/upload-artifact@v4.4.3
        with:
          name: SprintIndicator-${{ steps.shorten_commit_sha.outputs.shortened_commit_sha }}
          path: build/libs/*.jar
